# Generated by Django 2.2 on 2020-04-12 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='company_name',
            field=models.CharField(default='N/A', max_length=200, verbose_name='Company Name'),
        ),
    ]
