# Generated by Django 2.2 on 2020-04-12 13:06

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_agent_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='about',
            field=tinymce.models.HTMLField(default='', help_text='About me...'),
        ),
    ]
