# Generated by Django 2.2 on 2020-04-25 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0004_remove_agent_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='is_agent_model',
            field=models.BooleanField(default=True),
        ),
    ]
