# Generated by Django 2.2 on 2020-05-15 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0005_agent_is_agent_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='experience',
            field=models.CharField(default='', max_length=200, verbose_name='Experiance'),
        ),
    ]
