# Generated by Django 2.2 on 2020-05-19 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0006_agent_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='is_agent_model',
            field=models.BooleanField(default=True, editable=False),
        ),
    ]
