# Generated by Django 2.2 on 2020-02-07 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=1000, verbose_name='Name Of Location')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='listing_type',
            field=models.CharField(choices=[('For Sale', 'For Sale'), ('For Hire', 'For Hire')], default='', max_length=200, verbose_name='Listing Type'),
        ),
        migrations.AddField(
            model_name='product',
            name='mileage',
            field=models.CharField(default=0, max_length=200, verbose_name='Mileage'),
        ),
        migrations.AddField(
            model_name='product',
            name='location',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location', to='store.Location'),
        ),
    ]
