# Generated by Django 2.2 on 2020-03-17 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_companycontactdetails_quicklinks'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySocialMediaLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='Facebook Page Url')),
                ('twitter', models.URLField(blank=True, null=True, verbose_name='Twitter Page Url')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='Instagram Page Url')),
            ],
        ),
        migrations.AddField(
            model_name='quicklinks',
            name='link',
            field=models.URLField(default='', help_text='(e.g) www.necor.co.zm', verbose_name='Url'),
        ),
    ]
