# Generated by Django 2.2 on 2020-03-23 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20200317_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='posted_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
