# Generated by Django 2.2 on 2020-02-12 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20200207_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='listing_type',
            field=models.CharField(choices=[('For Sale', 'For Sale'), ('For Hire', 'For Hire'), ('Classified', 'Classified')], default='', max_length=200, verbose_name='Listing Type'),
        ),
    ]
