# Generated by Django 2.2 on 2020-04-08 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_event_venue'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='portfolio_site',
            field=models.URLField(blank=True),
        ),
    ]
