# Generated by Django 2.2 on 2020-04-13 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_auto_20200412_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='vehicle_status',
            field=models.CharField(choices=[('New', 'New'), ('Used', 'Used')], default='', max_length=200, verbose_name='Vehicle Status'),
        ),
        migrations.AddField(
            model_name='product',
            name='year',
            field=models.CharField(default=0, help_text='Year of Manufacture', max_length=200, verbose_name='Year'),
        ),
    ]
