# Generated by Django 2.2 on 2020-04-14 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_auto_20200413_1008'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Vehicle', 'verbose_name_plural': 'Vehicles'},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name': 'Vehicle Images', 'verbose_name_plural': 'Vehicle Images'},
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
