# Generated by Django 2.2 on 2020-04-25 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_auto_20200414_0517'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_event_model',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_vehicle_model',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='quicklinks',
            name='is_quicklinks_model',
            field=models.BooleanField(default=True),
        ),
    ]
