# Generated by Django 2.2 on 2020-03-17 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyContactDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Location')),
                ('mobile', models.CharField(blank=True, max_length=200, null=True, verbose_name='Mobile Phone Number')),
                ('telephone', models.CharField(blank=True, max_length=200, null=True, verbose_name='Telephone Number')),
                ('emailaddress1', models.CharField(blank=True, max_length=200, null=True, verbose_name='Email Address')),
                ('emailaddress2', models.CharField(blank=True, max_length=200, null=True, verbose_name='Email Address')),
            ],
        ),
        migrations.CreateModel(
            name='CompanySocialMediaLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='Facebook Page Url')),
                ('twitter', models.URLField(blank=True, null=True, verbose_name='Twitter Page Url')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='Instagram Page Url')),
            ],
        ),
    ]
