# Generated by Django 2.2 on 2020-03-17 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companycontactdetails',
            options={'verbose_name': 'Company Contact Detail', 'verbose_name_plural': 'Company Contact Details'},
        ),
        migrations.AlterModelOptions(
            name='companysocialmedialinks',
            options={'verbose_name': 'Company Social Media Link', 'verbose_name_plural': 'Company Social Media Links'},
        ),
        migrations.AlterField(
            model_name='companycontactdetails',
            name='emailaddress1',
            field=models.CharField(blank=True, help_text='(E.g) info@example1.com', max_length=200, null=True, verbose_name='Email Address1'),
        ),
        migrations.AlterField(
            model_name='companycontactdetails',
            name='emailaddress2',
            field=models.CharField(blank=True, help_text='(E.g) info@example1.com', max_length=200, null=True, verbose_name='Email Address2'),
        ),
        migrations.AlterField(
            model_name='companycontactdetails',
            name='location',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Company Location'),
        ),
        migrations.AlterField(
            model_name='companycontactdetails',
            name='mobile',
            field=models.CharField(blank=True, help_text='(E.g) +260970000000', max_length=200, null=True, verbose_name='Mobile Phone Number'),
        ),
        migrations.AlterField(
            model_name='companycontactdetails',
            name='telephone',
            field=models.CharField(blank=True, help_text='(E.g) +(0121) 121 122', max_length=200, null=True, verbose_name='Telephone Number'),
        ),
    ]
