# Generated by Django 2.2 on 2020-04-08 10:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0008_auto_20200408_1048'),
        ('businessdirectory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_type', models.CharField(max_length=200, verbose_name='Agent Type')),
            ],
            options={
                'verbose_name': 'Agent Type',
                'verbose_name_plural': 'Agent Types',
            },
        ),
        migrations.CreateModel(
            name='AutoShopAndCarWash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='name of car wash', max_length=200, verbose_name='Name')),
                ('location', models.CharField(help_text='location of car wash', max_length=200, verbose_name='Location')),
                ('contact', models.CharField(help_text='cell/tell/fax', max_length=200, verbose_name='Contact Details')),
                ('description', tinymce.models.HTMLField(help_text='Services offered...')),
                ('coverpic', models.ImageField(blank=True, null=True, upload_to='carwash/coverpic/%Y/%m/%d')),
                ('profilepic', models.ImageField(blank=True, null=True, upload_to='carwash/profilepic/%Y/%m/%d')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Category')),
            ],
            options={
                'verbose_name': 'Auto shops/Car wash/etc',
                'verbose_name_plural': 'Auto shops/Car wash/etc',
            },
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', tinymce.models.HTMLField(help_text='Services offered...')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Agent',
                'verbose_name_plural': 'Agents',
            },
        ),
    ]
