# Generated by Django 2.2 on 2020-04-08 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('businessdirectory', '0002_agent_agenttype_autoshopandcarwash'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='agent_type',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='businessdirectory.AgentType'),
        ),
    ]
