# Generated by Django 2.2 on 2020-04-12 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('businessdirectory', '0003_agent_agent_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Agent',
        ),
        migrations.DeleteModel(
            name='AgentType',
        ),
    ]
