# Generated by Django 2.2 on 2020-04-16 09:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('businessdirectory', '0007_equipment_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='user',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Agent Name'),
        ),
    ]
