# Generated by Django 2.2 on 2020-04-16 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businessdirectory', '0008_equipment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='equipment_brand',
            field=models.CharField(default='', max_length=200),
        ),
    ]
