# Generated by Django 2.2 on 2020-04-29 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businessdirectory', '0010_auto_20200425_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='equipment_listing_type',
            field=models.CharField(choices=[('For Sale', 'For Sale'), ('For Hire', 'For Hire'), ('Classified', 'Classified')], default='', max_length=200, verbose_name='Listing Type'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='equipment_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=100),
        ),
        migrations.AddField(
            model_name='equipment',
            name='equipment_sold',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='equipment_status',
            field=models.CharField(choices=[('New', 'New'), ('Used', 'Used')], default='', max_length=200, verbose_name='Equipment Status'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='equipment_stock',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
