# Generated by Django 2.2 on 2020-04-29 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businessdirectory', '0011_auto_20200429_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='is_equipment_model',
            field=models.BooleanField(default=True, editable=False),
        ),
    ]
