# Generated by Django 2.2 on 2020-05-15 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businessdirectory', '0012_auto_20200429_1005'),
    ]

    operations = [
        migrations.CreateModel(
            name='FillingStation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('location', models.CharField(max_length=200, verbose_name='Location')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='fillingstation/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='FinancialInstitutions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('location', models.CharField(max_length=200, verbose_name='Location')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='financialinstitution/%Y/%m/%d')),
            ],
        ),
    ]
