# Generated by Django 2.2 on 2020-05-15 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businessdirectory', '0013_fillingstation_financialinstitutions'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoshopandcarwash',
            name='facebook_link',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='autoshopandcarwash',
            name='instagram_link',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='autoshopandcarwash',
            name='twitter_link',
            field=models.URLField(default=''),
        ),
    ]
