# Generated by Django 2.2 on 2020-05-18 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businessdirectory', '0014_auto_20200515_0512'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoshopandcarwash',
            name='coordinates',
            field=models.CharField(default='zambia', help_text='Check name of the place on google maps or can use latitude and longitude (lati,longi)', max_length=200, verbose_name='Coordinates'),
        ),
    ]
