# Generated by Django 2.2 on 2020-05-18 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businessdirectory', '0015_autoshopandcarwash_coordinates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autoshopandcarwash',
            name='coordinates',
            field=models.CharField(default='', help_text='Check name of the place on google maps or can use latitude and longitude (lati,longi)', max_length=200, verbose_name='Coordinates'),
        ),
    ]
