# Generated by Django 2.2 on 2020-05-18 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businessdirectory', '0016_auto_20200518_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autoshopandcarwash',
            name='is_autoshopandcarwash_model',
            field=models.BooleanField(default=True, editable=False),
        ),
    ]
