# Generated by Django 2.2 on 2020-05-18 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businessdirectory', '0017_auto_20200518_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autoshopandcarwash',
            name='coordinates',
            field=models.CharField(blank=True, default='', help_text='Check name of the place on google maps or can use latitude and longitude (lati,longi)', max_length=200, null=True, verbose_name='Coordinates'),
        ),
        migrations.AlterField(
            model_name='autoshopandcarwash',
            name='facebook_link',
            field=models.URLField(default='www.facebook.com'),
        ),
        migrations.AlterField(
            model_name='autoshopandcarwash',
            name='instagram_link',
            field=models.URLField(default='www.instagram.com'),
        ),
        migrations.AlterField(
            model_name='autoshopandcarwash',
            name='twitter_link',
            field=models.URLField(default='www.twitter.com'),
        ),
    ]
