# Generated by Django 2.2 on 2020-05-21 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businessdirectory', '0018_auto_20200518_1348'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoEngineering',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('location', models.CharField(max_length=200, verbose_name='Location')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='fillingstation/%Y/%m/%d')),
                ('coordinates', models.CharField(blank=True, default='', help_text='Check name of the place on google maps or can use latitude and longitude (lati,longi)', max_length=200, null=True, verbose_name='Coordinates')),
                ('contact', models.CharField(max_length=200, verbose_name='Contact')),
                ('website_link', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EarthMoving',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('location', models.CharField(max_length=200, verbose_name='Location')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='fillingstation/%Y/%m/%d')),
                ('coordinates', models.CharField(blank=True, default='', help_text='Check name of the place on google maps or can use latitude and longitude (lati,longi)', max_length=200, null=True, verbose_name='Coordinates')),
                ('contact', models.CharField(max_length=200, verbose_name='Contact')),
                ('website_link', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MotorisedServices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('location', models.CharField(max_length=200, verbose_name='Location')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='fillingstation/%Y/%m/%d')),
                ('coordinates', models.CharField(blank=True, default='', help_text='Check name of the place on google maps or can use latitude and longitude (lati,longi)', max_length=200, null=True, verbose_name='Coordinates')),
                ('contact', models.CharField(max_length=200, verbose_name='Contact')),
                ('website_link', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('location', models.CharField(max_length=200, verbose_name='Location')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='fillingstation/%Y/%m/%d')),
                ('coordinates', models.CharField(blank=True, default='', help_text='Check name of the place on google maps or can use latitude and longitude (lati,longi)', max_length=200, null=True, verbose_name='Coordinates')),
                ('contact', models.CharField(max_length=200, verbose_name='Contact')),
                ('website_link', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transportation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('location', models.CharField(max_length=200, verbose_name='Location')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='fillingstation/%Y/%m/%d')),
                ('coordinates', models.CharField(blank=True, default='', help_text='Check name of the place on google maps or can use latitude and longitude (lati,longi)', max_length=200, null=True, verbose_name='Coordinates')),
                ('contact', models.CharField(max_length=200, verbose_name='Contact')),
                ('website_link', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='equipmentimage',
            name='featured',
        ),
        migrations.RemoveField(
            model_name='equipmentimage',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='autoshopandcarwash',
            name='website_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fillingstation',
            name='coordinates',
            field=models.CharField(blank=True, default='', help_text='Check name of the place on google maps or can use latitude and longitude (lati,longi)', max_length=200, null=True, verbose_name='Coordinates'),
        ),
        migrations.AddField(
            model_name='fillingstation',
            name='website_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialinstitutions',
            name='coordinates',
            field=models.CharField(blank=True, default='', help_text='Check name of the place on google maps or can use latitude and longitude (lati,longi)', max_length=200, null=True, verbose_name='Coordinates'),
        ),
        migrations.AddField(
            model_name='financialinstitutions',
            name='website_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
