# Generated by Django 2.2 on 2020-05-28 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('businessdirectory', '0021_auto_20200521_1053'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialInstitutionsDirectory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financial_institution_name', models.CharField(max_length=200, verbose_name='Financial Institution Name')),
            ],
        ),
        migrations.AlterField(
            model_name='financialinstitutions',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='businessdirectory.FillingStationDirectory', verbose_name='Name'),
        ),
    ]
