# Generated by Django 2.2 on 2020-05-28 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('businessdirectory', '0022_auto_20200528_0731'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FinancialInstitutions',
            new_name='FinancialInstitution',
        ),
        migrations.RenameModel(
            old_name='MotorisedServices',
            new_name='MotorisedService',
        ),
    ]
