# Generated by Django 2.2 on 2020-05-28 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businessdirectory', '0023_auto_20200528_0738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motorisedservice',
            name='picture',
            field=models.ImageField(blank=True, default='store/img/financial_institution_thumbnail.jpg', null=True, upload_to='fillingstation/%Y/%m/%d'),
        ),
    ]
