# Generated by Django 2.2 on 2020-05-28 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('businessdirectory', '0024_auto_20200528_0805'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FinancialInstitutionsDirectory',
            new_name='FinancialInstitutionDirectory',
        ),
    ]
