# Generated by Django 2.2 on 2020-05-28 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('businessdirectory', '0025_auto_20200528_0807'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fillingstationdirectory',
            options={'verbose_name_plural': 'Filling Stations Directory'},
        ),
        migrations.AlterModelOptions(
            name='financialinstitutiondirectory',
            options={'verbose_name_plural': 'Financial Institutions Directory'},
        ),
        migrations.AlterField(
            model_name='financialinstitution',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='businessdirectory.FinancialInstitutionDirectory', verbose_name='Name'),
        ),
    ]
