# Generated by Django 2.2 on 2020-05-28 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_auto_20200521_0653'),
        ('businessdirectory', '0026_auto_20200528_0813'),
    ]

    operations = [
        migrations.AddField(
            model_name='motorisedservice',
            name='city',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='store.Location', verbose_name='City/Town'),
        ),
        migrations.AlterField(
            model_name='motorisedservice',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='motorisedservice',
            name='picture',
            field=models.ImageField(blank=True, default='img/financial_institution_thumbnail.jpg', null=True, upload_to='fillingstation/%Y/%m/%d'),
        ),
    ]
