# Generated by Django 2.2 on 2020-05-28 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businessdirectory', '0027_auto_20200528_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motorisedservice',
            name='picture',
            field=models.ImageField(blank=True, default='img/financial_institution_thumbnail.png', null=True, upload_to='fillingstation/%Y/%m/%d'),
        ),
    ]
