# Generated by Django 2.2 on 2020-05-28 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businessdirectory', '0028_auto_20200528_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motorisedservice',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='fillingstation/%Y/%m/%d'),
        ),
    ]
