# Generated by Django 2.2 on 2020-05-28 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_auto_20200521_0653'),
        ('businessdirectory', '0029_auto_20200528_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoengineering',
            name='city',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='store.Location', verbose_name='City/Town'),
        ),
        migrations.AddField(
            model_name='earthmoving',
            name='city',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='store.Location', verbose_name='City/Town'),
        ),
        migrations.AddField(
            model_name='training',
            name='city',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='store.Location', verbose_name='City/Town'),
        ),
        migrations.AddField(
            model_name='transportation',
            name='city',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='store.Location', verbose_name='City/Town'),
        ),
        migrations.AlterField(
            model_name='autoengineering',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='autoengineering/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='motorisedservice',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='motorizedservices/%Y/%m/%d'),
        ),
    ]
