# Generated by Django 2.2 on 2020-06-01 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('businessdirectory', '0030_auto_20200528_1002'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autoengineering',
            options={'verbose_name_plural': 'Auto Engineering Services'},
        ),
        migrations.AlterModelOptions(
            name='earthmoving',
            options={'verbose_name_plural': 'Earth Moving Services'},
        ),
        migrations.AlterModelOptions(
            name='training',
            options={'verbose_name_plural': 'Training Services'},
        ),
        migrations.AlterModelOptions(
            name='transportation',
            options={'verbose_name_plural': 'Transportation Services'},
        ),
    ]
