# Generated by Django 2.2 on 2020-06-01 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businessdirectory', '0031_auto_20200601_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
        migrations.AddField(
            model_name='equipmenttype',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
    ]
