# Generated by Django 2.2 on 2020-06-01 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businessdirectory', '0032_auto_20200601_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='fillingstationdirectory',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
    ]
