# Generated by Django 2.2 on 2020-06-01 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businessdirectory', '0033_fillingstationdirectory_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='fillingstation',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
        migrations.AddField(
            model_name='financialinstitution',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
        migrations.AddField(
            model_name='financialinstitutiondirectory',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
    ]
