# Generated by Django 2.2 on 2020-06-01 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businessdirectory', '0035_auto_20200601_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='motorisedservice',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
    ]
