# Generated by Django 2.2 on 2020-06-02 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businessdirectory', '0036_motorisedservice_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoengineering',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
        migrations.AddField(
            model_name='earthmoving',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
        migrations.AddField(
            model_name='training',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
        migrations.AddField(
            model_name='transportation',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
    ]
