# Generated by Django 2.2 on 2020-06-02 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businessdirectory', '0037_auto_20200602_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoshopandcarwash',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
    ]
