# Generated by Django 2.2 on 2020-04-14 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(default='123abc', editable=False, max_length=200, unique=True)),
                ('sub_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=1000)),
                ('tax_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=1000)),
                ('final_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=1000)),
                ('status', models.CharField(choices=[('Started', 'Started'), ('Abandoned', 'Abandoned'), ('Finished', 'Finished')], default='Started', max_length=200)),
                ('contact_name', models.CharField(help_text='This field is required', max_length=200, verbose_name='Contact Name (Optional)')),
                ('country_region', models.CharField(help_text='This field is required', max_length=200, verbose_name='Country/Region')),
                ('street_address', models.TextField(help_text='This field is required', max_length=200, verbose_name='Street Address')),
                ('phone_number', models.CharField(help_text='This field is required', max_length=200, verbose_name='Phone Number')),
                ('city', models.CharField(max_length=200, verbose_name='City')),
                ('state_province_region', models.CharField(max_length=200, verbose_name='State/Province/Region')),
                ('zip_postal_code', models.CharField(max_length=200, verbose_name='Zip Code')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
