# Generated by Django 2.2 on 2020-04-14 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='state_province_region',
        ),
        migrations.RemoveField(
            model_name='order',
            name='zip_postal_code',
        ),
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(default='', help_text='This field is required', max_length=200, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='order',
            name='province',
            field=models.CharField(default='', max_length=200, verbose_name='Province'),
        ),
        migrations.AlterField(
            model_name='order',
            name='contact_name',
            field=models.CharField(help_text='This field is required', max_length=200, verbose_name='Contact Name (Full Name)'),
        ),
    ]
