# Generated by Django 2.2 on 2020-05-14 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_vehicle_of_interest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='vehicle_of_interest',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='store.Product'),
        ),
    ]
