# Generated by Django 2.2 on 2020-05-19 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_order_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='vehicle_of_interest',
            field=models.OneToOneField(default='', help_text='Do not change this field', on_delete=django.db.models.deletion.CASCADE, to='store.Product'),
        ),
    ]
