# Generated by Django 2.2 on 2020-06-10 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_productreview'),
        ('orders', '0007_auto_20200519_0927'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentOrder',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('order_id', models.IntegerField(default=0)),
                ('sub_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=1000)),
                ('tax_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=1000)),
                ('final_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=1000)),
                ('status', models.CharField(choices=[('Started', 'Started'), ('Abandoned', 'Abandoned'), ('Finished', 'Finished')], default='Started', max_length=200)),
                ('contact_name', models.CharField(help_text='This field is required', max_length=200, verbose_name='Contact Name (Full Name)')),
                ('country_region', models.CharField(help_text='This field is required', max_length=200, verbose_name='Country/Region')),
                ('province', models.CharField(default='', max_length=200, verbose_name='Province')),
                ('city', models.CharField(max_length=200, verbose_name='City')),
                ('street_address', models.TextField(help_text='This field is required', max_length=200, verbose_name='Street Address')),
                ('phone_number', models.CharField(help_text='This field is required', max_length=200, verbose_name='Phone Number')),
                ('email', models.EmailField(default='', help_text='This field is required', max_length=200, verbose_name='Email')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehicle_of_interest', models.OneToOneField(default='', help_text='Do not change this field', on_delete=django.db.models.deletion.CASCADE, to='store.Product')),
            ],
        ),
    ]
