# Generated by Django 2.2 on 2020-06-10 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('businessdirectory', '0038_autoshopandcarwash_slug'),
        ('orders', '0010_auto_20200610_1255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipmentorder',
            name='vehicle_of_interest',
        ),
        migrations.AddField(
            model_name='equipmentorder',
            name='equipment_of_interest',
            field=models.ForeignKey(default='', help_text='Do not change this field', on_delete=django.db.models.deletion.CASCADE, to='businessdirectory.Equipment'),
        ),
        migrations.AlterField(
            model_name='order',
            name='vehicle_of_interest',
            field=models.ForeignKey(default='', help_text='Do not change this field', on_delete=django.db.models.deletion.CASCADE, to='store.Product'),
        ),
    ]
